### ISSUE TITLE
Sun Exposure results are of old design

### ISSUE THREAD

**Issue by JLSievert** [grasbrook-cityscope/functionalscope#101]
The "scenario" for sun exposure for GB is of the old design (on hcu-dev). Any chance this can be updated to fit the "new" ie final disign?

![grafik](https://user-images.githubusercontent.com/45463490/145585130-c0437e16-5e87-4a92-95f6-7c3b6ccde384.png)

**Comment by andredaa** [comment]
well. i wouldnt call that a bug. we simply never had send the new design to sun calculation.

**Comment by andredaa** [comment]
Fixed
