### ISSUE TITLE
"Cut out" Wind and Noise results layers with design area boundaries

### ISSUE THREAD

**Issue by JLSievert** [grasbrook-cityscope/functionalscope#103]
"Punch" / cut out the Wind and Noise results using the GB design area boundaries, as is done for Sun. It used to be like this for Wind in an earlier version.
Noise [Screenshot from 15.12.2021]
![grafik](https://user-images.githubusercontent.com/45463490/146195402-3589f719-f494-4799-8df6-a360714b13d3.png)
Wind [Screenshot from 15.12.2021]
![grafik](https://user-images.githubusercontent.com/45463490/146196021-b695b088-6999-464f-82ae-010012315d8b.png)

-> it should look more like this... (e.g. earlier version of wind)
![grafik](https://user-images.githubusercontent.com/45463490/146195610-176aa7fa-eeb1-4440-9c7e-5d435ce64b1e.png)

**Comment by andredaa** [comment]
fixed for wind.

**Comment by andredaa** [comment]
fixed for noise.
