### ISSUE TITLE
Hide "Change Selection" button on ABM graph.

### ISSUE THREAD

**Issue by JLSievert** [grasbrook-cityscope/functionalscope#53]
Hide the "Change Selection" / "Compare by Transit Mode" button on the ABM graph. This button is a sort of filter for different mobility types, but since this is a simulation of pedestrian movement only, the choice of categories is confusing to users. This feature might come in handy in the feature. This feature will also likely be affected by updates to the data export  format from GAMA.

![grafik](https://user-images.githubusercontent.com/45463490/134541066-7a74af85-a576-4c68-8e68-314311c52063.png)

**Comment by totev** [comment]
So does this mean, that the button should stay visible for the other scenarios/graphs?

**Comment by JLSievert** [comment]
No, it shouldn't stay visible for the other scenarios/graphs. Now, It is only visible for ABM. We don't have plans to include it in the stormwater graph. The other modules do not include the graph.
