### ISSUE TITLE
Reevaluate eslint rules 

### ISSUE THREAD

**Issue by totev** [grasbrook-cityscope/functionalscope#57]
The current set of eslint linting rules seems very strict and is currently not enforced.

Maybe we should re-examine them and/or start a new with the least amount of recommended settings and work our way up from there?

<img width="1519" alt="Screenshot 2021-09-24 at 11 17 53" src="https://user-images.githubusercontent.com/4454638/134650705-544d2851-b2d5-4214-845b-adf13a684067.png">

**Comment by andredaa** [comment]
The problem is, i never wanted to loose the history via git blame for each line.
It all started with me and Bird having different rules and Bird saying "i know i format right - i dont need the linter" :p 
I like your suggestion: Maybe we can look at it on monday? So we agree on a base of rules?

**Comment by totev** [comment]
Let's do this 👍 
My current issue is that it makes it almost impossible to work with all of the red going on in the code base :)
