### ISSUE TITLE
Stormwater Calculation Request Failed 500, functionalscope..rocks branch

### ISSUE THREAD

**Issue by JLSievert** [grasbrook-cityscope/functionalscope#61]
Stormwater module not working? Is this just because it's a dev branch?
![grafik](https://user-images.githubusercontent.com/45463490/135588656-b19555e4-9c29-4804-839f-e22a5cb56594.png)

**Comment by totev** [comment]
Looks like a backend thing. Mabe @andredaa  can have a look at it?
![Screenshot 2021-10-01 at 10 26 37](https://user-images.githubusercontent.com/4454638/135589413-09bd31ee-06d1-4689-bbb2-f9fdba80b6d9.png)

**Comment by andredaa** [comment]
ah - the user was missing the subcatchments.json
i had only been working with the testUser so far.
