### ISSUE TITLE
Features to throw away

### ISSUE THREAD

**Issue by andredaa** [grasbrook-cityscope/functionalscope#89]
@JLSievert  Hello :))
i am trying to throw some weight/technical dept over board. What do you think about these questions?

We no longer need ABM Filters right? To filter agents by age, modality etc? That would save a huge chunk of spaghetti in which we separate "active" abm sets from the unfiltered one. Plus data preparation for faster filtering and storing huge lookup tables in memory and so on.  --> Time Filter should still work! Might be intertwined with the other filters? 
  
Do we need the relative data heatmap or should we throw the code for it away?
To be honest I never really understood the difference between them (same data displayed different way, no comments)
![image](https://user-images.githubusercontent.com/4631906/141790385-0fe182ed-0d3a-4cc9-bee1-9ab5ba1a4420.png)

Do we need the arcs?
![image](https://user-images.githubusercontent.com/4631906/141790519-9b011dec-9e02-48f5-a760-5b9470020d69.png)

Do we need the ABM and Amenity Stats?

**Comment by andredaa** [comment]
@JLSievert  - Do you have an opinion on which ones we can delete?

**Comment by JLSievert** [comment]
@andredaa go ahead and delete the ones you listed: Filtering + relative data heatmeap. We only need to display one version of the headmap layer.

**Comment by andredaa** [comment]
thank you :) what about the arcs and the abm + amenity stats? i guess the stats we need to keep in some way - but display them more nicely?
@JLSievert

**Comment by andredaa** [comment]
keep abm and amenity stats.
delete relative data heatmap

**Comment by andredaa** [comment]
i am also going to delete the modal with info about the amenities,.
![image](https://user-images.githubusercontent.com/4631906/144453700-80a44654-7bf4-437d-9798-aade0de4adda.png)

OK? @JLSievert

**Comment by JLSievert** [comment]
Ok! @andredaa

**Comment by andredaa** [comment]
cool :) https://github.com/grasbrook-cityscope/functionalscope/commit/82cb0188abda07071cfef61fab474247fce0cde6
