### ISSUE TITLE
Hide ABM graph if no scenario has been run yet

### ISSUE THREAD

**Issue by JLSievert** [grasbrook-cityscope/functionalscope#98]
Currently, when you enter the tool or click on "Pedestrians"button, even before a scenario has been loaded, the graph is visible. The graph in the bottom left should only appear after a scenario has been run (after the user clicks on "Run Scenario"). 

![grafik](https://user-images.githubusercontent.com/45463490/145579758-142c765b-311a-4957-bfa3-a0b59c0c0113.png)

**Comment by andredaa** [comment]
done with 8570344959f25ff10482bb326017aef9c8d0ae37
