### ISSUE TITLE
Loading of wind results is confusing

### ISSUE THREAD

**Issue by JLSievert** [grasbrook-cityscope/functionalscope#99]
After selecting a a completely new wind scenario, but before the results have loaded, the user is currently able to select different scenarios (both "saved" scenarios and another new scenario). Then as the results come in for the other secenario, they appear instead of the other selected results. At that point, it's not clear what the resulting map is representing.
 
Possible improvements might include: 

- add loading screen like for ABM, either only on top of the right side panel or ontop of the map, too.
- don't allow user to to select a different (new) wind scenario while the results of a previous scenario are still being loaded
- display the wind scenario information underneath / to the left of the "save" save button, so that the user is reassured they are saving the right scenario (something like  what we have in the "combine layers" section)

@totev @andredaa : any other ideas for solving this issue? / do I understand the issue correctly?

What's going on in this screenshot? I had selected a new scenario with very high windspeeds, close to 80 kmh. Then, I clicked on the "Annual Average" scenario and the scenario settings reset -- but the "Annual Aaverage" scenario didn't load, because the frontend was still waiting on the results of the pending simulation. When the results of the high-wind scenario came in, they no longer matched the scenario setttings displayed. This is confusing.

![grafik](https://user-images.githubusercontent.com/45463490/145583139-5de53caa-674a-4f5b-b592-eb38a005f0fd.png)

**Comment by andredaa** [comment]
Cool! I would suggest to solve it with a loading screen that blocks the user from changing the settings or loading a saved scneario? 
For the other topics we mark the setting fields red, if they are not longer matching the displayed results (if the form is dirty ;) ). We should do that here as well.  Also i like the idea of displaing the currently shown values under "save scenario".

**Comment by totev** [comment]
We can do both - loading screen and disabling the form (its submission) while loading the results :) Also adding the same dirty/pristine form handling and look and feel across all of our forms can't hurt the look and feel and the intuitive user workflow.

**Comment by andredaa** [comment]
https://github.com/grasbrook-cityscope/functionalscope/pull/102

**Comment by JLSievert** [comment]
Loading screen like ABM: 
![grafik](https://user-images.githubusercontent.com/45463490/146761032-4a84b40c-a666-43a2-86d2-f36ecc439af4.png)
In the case of ABM, the user isn't allowed to click away to a different module. However, for simulations that take up to 2 minutes, like wind, it would be good if users can click around and explore other modules while they are waiting for the results to load. That means, YES to dark loading screen when on wind + selection of new criteria disabled. NO to disabling the full righthand menu.
- replace text with e.g. "Getting wind results from InFraRed. Results can take up to 2 minutes."
- add button loading style (or similar) to the "Wind" button when results have been returned. This indicates to users that new results are available. E.g. same style as for "Run Scenario" button that appears when the user defines a new scenario. 
![grafik](https://user-images.githubusercontent.com/45463490/146761443-beb0495f-96fd-4c8f-aeda-e93740b45f8e.png)

**Comment by andredaa** [comment]
Done.
@totev https://github.com/grasbrook-cityscope/functionalscope/blob/3b9c746ba8dd4df7d0ef335c4800c64ed5834af6/src/components/Scenario/Wind.vue#L343  --->I want to add a v-if here for  the variable "windResult". However, if i do this, the windResult mutation will not be excecuted, if the user meanwhile switched to another menu-tab. Somehow it seems to block the store?? it took me 3hours to find out this causes the error. Honestly sometimes front-end just drives you mad.

**Comment by andredaa** [comment]
102

**Comment by totev** [comment]
@andredaa Regarding the blocked mutation - can we debug it together? I think trying to reproduce it on my own is going to take longer than if we just had a remote coding session.

**Comment by andredaa** [comment]
i found another solution that is just as good. :) just looking whether the layer is visible or not.
